services:
  mysql:
    image: mysql:8.0
    container_name: chatop-mysql
    environment:
      MYSQL_DATABASE: chatop
      MYSQL_ROOT_PASSWORD: "" # Up to you to set a root password or leave it empty
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      # Mount the initialization script
      - ../ressources/sql/script.sql:/docker-entrypoint-initdb.d/01-init.sql
      # Persist MySQL data
      - chatop-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower-case-table-names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 3s

volumes:
  chatop-mysql-data:
